package com.hrbb.loan.pos.dao;

import java.util.List;
import java.util.Map;

import com.hrbb.loan.pos.dao.entity.TAsynchronousNotification;

public interface TAsynchronousNotificationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asynchronous_notification
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asynchronous_notification
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    int insert(TAsynchronousNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asynchronous_notification
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    int insertSelective(TAsynchronousNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asynchronous_notification
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    TAsynchronousNotification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asynchronous_notification
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    int updateByPrimaryKeySelective(TAsynchronousNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_asynchronous_notification
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    int updateByPrimaryKey(TAsynchronousNotification record);
    
    int updateSatusByPrimaryKey(String status,int id);
    
    public List<TAsynchronousNotification> selectSelective(Map<String, Object> map);
    
    public List<TAsynchronousNotification> selectTodoList(Map<String, Object> map);
}