package com.hrbb.loan.pos.service;

import java.util.List;
import java.util.Map;

import com.hrbb.loan.pos.dao.entity.TMailNotification;

public interface TMailNotificationService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail_notification
     *
     * @mbggenerated Fri Sep 04 23:18:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail_notification
     *
     * @mbggenerated Fri Sep 04 23:18:19 CST 2015
     */
    int insert(TMailNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail_notification
     *
     * @mbggenerated Fri Sep 04 23:18:19 CST 2015
     */
    int insertSelective(TMailNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail_notification
     *
     * @mbggenerated Fri Sep 04 23:18:19 CST 2015
     */
    TMailNotification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail_notification
     *
     * @mbggenerated Fri Sep 04 23:18:19 CST 2015
     */
    int updateByPrimaryKeySelective(TMailNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mail_notification
     *
     * @mbggenerated Fri Sep 04 23:18:19 CST 2015
     */
    int updateByPrimaryKey(TMailNotification record);
    
    public List<TMailNotification> selectTodoList();

    int updateCount(Map<String, Object> map);
}