package com.hrbb.loan.pos.dao.entity;

public class TCnapsRelative {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_cnaps_relative.relativeNo
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    private String relativeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_cnaps_relative.relativeName
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    private String relativename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_cnaps_relative.remark
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_cnaps_relative.relativeNo
     *
     * @return the value of t_cfg_cnaps_relative.relativeNo
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    public String getRelativeno() {
        return relativeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_cnaps_relative.relativeNo
     *
     * @param relativeno the value for t_cfg_cnaps_relative.relativeNo
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    public void setRelativeno(String relativeno) {
        this.relativeno = relativeno == null ? null : relativeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_cnaps_relative.relativeName
     *
     * @return the value of t_cfg_cnaps_relative.relativeName
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    public String getRelativename() {
        return relativename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_cnaps_relative.relativeName
     *
     * @param relativename the value for t_cfg_cnaps_relative.relativeName
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    public void setRelativename(String relativename) {
        this.relativename = relativename == null ? null : relativename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_cnaps_relative.remark
     *
     * @return the value of t_cfg_cnaps_relative.remark
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_cnaps_relative.remark
     *
     * @param remark the value for t_cfg_cnaps_relative.remark
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}