package com.hrbb.loan.pos.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TApplyNotify {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.loanId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String loanId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.bizLoanId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String bizLoanId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.channel
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String channel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.custName
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String custName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.posCustName
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String posCustName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.beginDate
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private Date beginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.applyAmt
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private BigDecimal applyAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.repayMethod
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String repayMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.paybackWay
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String paybackWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.applyStatus
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String applyStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.region
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String region;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.paperId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String paperId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.mobilePhone
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String mobilePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.apprResult
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String apprResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.apprEndTime
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private Date apprEndTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.apprAmt
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private BigDecimal apprAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.apprInt
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private BigDecimal apprInt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.apprRepayMethod
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String apprRepayMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.apprId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String apprId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_apply_notify.refuseReason
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	private String refuseReason;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.loanId
	 * @return  the value of t_apply_notify.loanId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getLoanId() {
		return loanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.loanId
	 * @param loanId  the value for t_apply_notify.loanId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setLoanId(String loanId) {
		this.loanId = loanId == null ? null : loanId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.bizLoanId
	 * @return  the value of t_apply_notify.bizLoanId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getBizLoanId() {
		return bizLoanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.bizLoanId
	 * @param bizLoanId  the value for t_apply_notify.bizLoanId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setBizLoanId(String bizLoanId) {
		this.bizLoanId = bizLoanId == null ? null : bizLoanId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.channel
	 * @return  the value of t_apply_notify.channel
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.channel
	 * @param channel  the value for t_apply_notify.channel
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setChannel(String channel) {
		this.channel = channel == null ? null : channel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.custName
	 * @return  the value of t_apply_notify.custName
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getCustName() {
		return custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.custName
	 * @param custName  the value for t_apply_notify.custName
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setCustName(String custName) {
		this.custName = custName == null ? null : custName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.posCustName
	 * @return  the value of t_apply_notify.posCustName
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getPosCustName() {
		return posCustName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.posCustName
	 * @param posCustName  the value for t_apply_notify.posCustName
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setPosCustName(String posCustName) {
		this.posCustName = posCustName == null ? null : posCustName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.beginDate
	 * @return  the value of t_apply_notify.beginDate
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public Date getBeginDate() {
		return beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.beginDate
	 * @param beginDate  the value for t_apply_notify.beginDate
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.applyAmt
	 * @return  the value of t_apply_notify.applyAmt
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public BigDecimal getApplyAmt() {
		return applyAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.applyAmt
	 * @param applyAmt  the value for t_apply_notify.applyAmt
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setApplyAmt(BigDecimal applyAmt) {
		this.applyAmt = applyAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.repayMethod
	 * @return  the value of t_apply_notify.repayMethod
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getRepayMethod() {
		return repayMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.repayMethod
	 * @param repayMethod  the value for t_apply_notify.repayMethod
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setRepayMethod(String repayMethod) {
		this.repayMethod = repayMethod == null ? null : repayMethod.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.paybackWay
	 * @return  the value of t_apply_notify.paybackWay
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getPaybackWay() {
		return paybackWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.paybackWay
	 * @param paybackWay  the value for t_apply_notify.paybackWay
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setPaybackWay(String paybackWay) {
		this.paybackWay = paybackWay == null ? null : paybackWay.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.applyStatus
	 * @return  the value of t_apply_notify.applyStatus
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getApplyStatus() {
		return applyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.applyStatus
	 * @param applyStatus  the value for t_apply_notify.applyStatus
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setApplyStatus(String applyStatus) {
		this.applyStatus = applyStatus == null ? null : applyStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.region
	 * @return  the value of t_apply_notify.region
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.region
	 * @param region  the value for t_apply_notify.region
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setRegion(String region) {
		this.region = region == null ? null : region.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.paperId
	 * @return  the value of t_apply_notify.paperId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getPaperId() {
		return paperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.paperId
	 * @param paperId  the value for t_apply_notify.paperId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setPaperId(String paperId) {
		this.paperId = paperId == null ? null : paperId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.mobilePhone
	 * @return  the value of t_apply_notify.mobilePhone
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getMobilePhone() {
		return mobilePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.mobilePhone
	 * @param mobilePhone  the value for t_apply_notify.mobilePhone
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.apprResult
	 * @return  the value of t_apply_notify.apprResult
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getApprResult() {
		return apprResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.apprResult
	 * @param apprResult  the value for t_apply_notify.apprResult
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setApprResult(String apprResult) {
		this.apprResult = apprResult == null ? null : apprResult.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.apprEndTime
	 * @return  the value of t_apply_notify.apprEndTime
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public Date getApprEndTime() {
		return apprEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.apprEndTime
	 * @param apprEndTime  the value for t_apply_notify.apprEndTime
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setApprEndTime(Date apprEndTime) {
		this.apprEndTime = apprEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.apprAmt
	 * @return  the value of t_apply_notify.apprAmt
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public BigDecimal getApprAmt() {
		return apprAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.apprAmt
	 * @param apprAmt  the value for t_apply_notify.apprAmt
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setApprAmt(BigDecimal apprAmt) {
		this.apprAmt = apprAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.apprInt
	 * @return  the value of t_apply_notify.apprInt
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public BigDecimal getApprInt() {
		return apprInt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.apprInt
	 * @param apprInt  the value for t_apply_notify.apprInt
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setApprInt(BigDecimal apprInt) {
		this.apprInt = apprInt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.apprRepayMethod
	 * @return  the value of t_apply_notify.apprRepayMethod
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getApprRepayMethod() {
		return apprRepayMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.apprRepayMethod
	 * @param apprRepayMethod  the value for t_apply_notify.apprRepayMethod
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setApprRepayMethod(String apprRepayMethod) {
		this.apprRepayMethod = apprRepayMethod == null ? null : apprRepayMethod
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.apprId
	 * @return  the value of t_apply_notify.apprId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getApprId() {
		return apprId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.apprId
	 * @param apprId  the value for t_apply_notify.apprId
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setApprId(String apprId) {
		this.apprId = apprId == null ? null : apprId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_apply_notify.refuseReason
	 * @return  the value of t_apply_notify.refuseReason
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public String getRefuseReason() {
		return refuseReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_apply_notify.refuseReason
	 * @param refuseReason  the value for t_apply_notify.refuseReason
	 * @mbggenerated  Sun Sep 06 23:56:32 CST 2015
	 */
	public void setRefuseReason(String refuseReason) {
		this.refuseReason = refuseReason == null ? null : refuseReason.trim();
	}
}