package com.hrbb.loan.pos.dao;

import com.hrbb.loan.pos.dao.entity.TCnapsRelative;

public interface TCnapsRelativeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_cnaps_relative
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    int deleteByPrimaryKey(String objectNo,String objectType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_cnaps_relative
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    int insert(TCnapsRelative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_cnaps_relative
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    int insertSelective(TCnapsRelative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_cnaps_relative
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    TCnapsRelative selectByPrimaryKey(String objectNo,String objectType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_cnaps_relative
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    int updateByPrimaryKeySelective(TCnapsRelative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_cnaps_relative
     *
     * @mbggenerated Sun Aug 30 14:58:40 CST 2015
     */
    int updateByPrimaryKey(TCnapsRelative record);
}